stages:
  preprocess:
    cmd: python project/preprocess.py
    deps:
      - project/preprocess.py
    outs:
      - data/processed_data.csv

  train:
    cmd: python project/train.py
    deps:
      - data/processed_data.csv
      - project/train.py
    outs:
      - models/kmeans_model.pkl
      - models/dbscan_model.pkl
      - models/hierarchical_model.pkl
      - data/clustered_data.csv

  evaluate:
    cmd: python project/evaluate.py
    deps:
      - project/evaluate.py
      - data/clustered_data.csv
      - models/kmeans_model.pkl
      - models/dbscan_model.pkl
      - models/hierarchical_model.pkl
    outs:
      - metrics/evaluation_metrics.json
